# Generated by Django 5.0.4 on 2024-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='aadhar_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='address',
            field=models.TextField(default=0),
        ),
    ]
