# Generated by Django 5.0.4 on 2024-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_userregistration_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='vehicle_name',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='aadhar_card',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='address',
            field=models.TextField(),
        ),
    ]
