# Generated by Django 5.0.4 on 2024-04-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_userregistration_vehicle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='vehicle_name',
            field=models.CharField(max_length=10),
        ),
    ]
